#!/bin/bash

colorOff="\033[0m"
redBold="\e[31m\e[1m"
greenBold="\e[32m\e[1m"

echo "Running tests before commit..."
echo "If the tests fail, the commit will be aborted."

mvnResult=$(mvn clean test)

if [ $? -ne 0 ]
  then
  printf "${redBold}Tests failed. The commit was aborted.${colorOff}\n"
  echo
  exit 1
else
  printf "${greenBold}Tests passed.${colorOff}\n"
  echo
fi
